FROM node:18-alpine3.17 as build-stage

WORKDIR /app

COPY package*.json /app/
RUN npm install
COPY . .
COPY public/ public/
COPY tsconfig.json .
COPY tailwind.config.js .

ENV BACKEND_PROXY=http://wenjim-backend-prod:5000

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
