# To be ran with the Flask version
version: '3'

services:
  psql:
    container_name: psql-flask
    image: postgres:16.1-alpine3.17
    volumes:
      - ./data/sql:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"

networks:
  wenjim:
