services:
  scraper:
    build: .
    restart: "no"
    env_file:
      - ../../.env
    depends_on:
      psql:
        condition: service_healthy
  psql:
    container_name: psql-scraper
    image: postgres:16.1-alpine3.17
    volumes:
      - ../data/sql:/var/lib/postgresql/data
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 3s
      retries: 5
